/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'caios' at '7/29/16 11:57 AM' with Gradle 2.14
 *
 * @author caios, @date 7/29/16 11:57 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
